/**
 * SocialLead Pro - Initial Seed Database
 * Contains rich sample leads with extracted emails, WA numbers, locations, and handles.
 */

const SAMPLE_LEADS = [
  {
    id: 'lead-1',
    platform: 'facebook',
    platformName: 'Facebook',
    name: 'Butik Fashion Elegant Jakarta',
    handle: '@butikelegant.official',
    url: 'https://facebook.com/butikelegant.official',
    email: 'contact@butikelegant.com',
    phone: '+6281234567890',
    wa: '6281234567890',
    address: 'Jl. Tanah Abang Blok A No. 45, Jakarta Pusat',
    city: 'Jakarta',
    followers: '45.2K',
    bio: 'Pusat Fashion Wanita & Hijab Premium Grosir / Eceran. Fast Response Order via WhatsApp!',
    scrapedAt: '2026-07-30 06:15'
  },
  {
    id: 'lead-2',
    platform: 'instagram',
    platformName: 'Instagram',
    name: 'Grosir Baju Hijab Surabaya',
    handle: '@hijabgrosir_surabaya',
    url: 'https://instagram.com/hijabgrosir_surabaya',
    email: 'admin@grosirhijabsby.co.id',
    phone: '+6285711223344',
    wa: '6285711223344',
    address: 'Jl. Pemuda No. 88, Surabaya, Jawa Timur',
    city: 'Surabaya',
    followers: '128.5K',
    bio: 'Produsen Hijab Kekinian Supplier Olshop termurah. Order Klik Link WA di Bio!',
    scrapedAt: '2026-07-30 06:18'
  },
  {
    id: 'lead-3',
    platform: 'tiktok',
    platformName: 'TikTok',
    name: 'Skincare Glowing ID',
    handle: '@glowing_skincare_id',
    url: 'https://tiktok.com/@glowing_skincare_id',
    email: 'partnership@glowingskincare.id',
    phone: '+6281908070605',
    wa: '6281908070605',
    address: 'Ruko BSD City Sector 7 No. 12, Tangerang Selatan',
    city: 'Tangerang',
    followers: '540K',
    bio: 'BPOM Approved Skin Care. Open Reseller & Affiliate Seluruh Indonesia. WA Admin di bawah 👇',
    scrapedAt: '2026-07-30 06:20'
  },
  {
    id: 'lead-4',
    platform: 'google',
    platformName: 'Google Business / Maps',
    name: 'Kopi Kenangan Resto & Cafe Jogja',
    handle: 'Google Maps Place ID: 87391',
    url: 'https://maps.google.com/?q=Kopi+Kenangan+Resto+Jogja',
    email: 'help@kopikenanganresto.com',
    phone: '+6281399887766',
    wa: '6281399887766',
    address: 'Jl. Malioboro No. 102, Sosromenduran, Yogyakarta',
    city: 'Yogyakarta',
    followers: '4.8 ★ (1,240 Reviews)',
    bio: 'Tempat Nongkrong Hits Malioboro, Coffee, Pastry & Modern Indonesian Cuisine.',
    scrapedAt: '2026-07-30 06:22'
  },
  {
    id: 'lead-5',
    platform: 'facebook',
    platformName: 'Facebook',
    name: 'Distro Apparel Bandung',
    handle: '@distrobandung_store',
    url: 'https://facebook.com/distrobandung_store',
    email: 'sales@distrobandungapparel.com',
    phone: '+6282144556677',
    wa: '6282144556677',
    address: 'Jl. Riau No. 14, Citarum, Bandung',
    city: 'Bandung',
    followers: '89.1K',
    bio: 'Original Streetwear & Custom T-Shirt Print. Pengiriman Harian ke Seluruh Indonesia.',
    scrapedAt: '2026-07-30 06:24'
  },
  {
    id: 'lead-6',
    platform: 'youtube',
    platformName: 'YouTube',
    name: 'Gadget Reviewer Indonesia',
    handle: '@gadgetreview_id',
    url: 'https://youtube.com/@gadgetreview_id',
    email: 'business@gadgetreviewid.com',
    phone: '+6281122334455',
    wa: '6281122334455',
    address: 'Menara Palma Lt. 18, Kuningan, Jakarta Selatan',
    city: 'Jakarta',
    followers: '1.2M Subs',
    bio: 'Ulasan HP & Teknologi Terbaru Setiap Hari. Endorsement / Business Inquiry email kami.',
    scrapedAt: '2026-07-30 06:25'
  },
  {
    id: 'lead-7',
    platform: 'instagram',
    platformName: 'Instagram',
    name: 'Kue & Catering Mamaku Semarang',
    handle: '@cateringmama_smg',
    url: 'https://instagram.com/cateringmama_smg',
    email: 'order@cateringmamasmg.com',
    phone: '+6285290001122',
    wa: '6285290001122',
    address: 'Jl. Pandanaran No. 56, Semarang',
    city: 'Semarang',
    followers: '32.4K',
    bio: 'Nasi Box, Snack Box, Prasmanan Nikahan & Acara Kantor Semarang. Hubungi WA 085290001122',
    scrapedAt: '2026-07-30 06:26'
  },
  {
    id: 'lead-8',
    platform: 'tiktok',
    platformName: 'TikTok',
    name: 'Sepatu Sneaker Hype Bali',
    handle: '@sneakerhype_bali',
    url: 'https://tiktok.com/@sneakerhype_bali',
    email: 'sneakerbali@gmail.com',
    phone: '+6287861009988',
    wa: '6287861009988',
    address: 'Jl. Sunset Road No. 77, Kuta, Bali',
    city: 'Bali',
    followers: '210K',
    bio: '100% Authentic Sneakers Import, Jordan, Yeezy, Nike Dunk. COD Bali Available.',
    scrapedAt: '2026-07-30 06:26'
  }
];
